AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AutoOps contains useful operational processes represented as a state
  machines with AWS StepFunctions.

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOps
    Description: A toolkit for auto ops in AWS.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: s3://597377428377/AutoOps/8bcffc30d2cb495886190c400aef88b2
    Labels:
    - tests
    SemanticVersion: 0.0.1
Resources:
  EBSScalingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri:
        Bucket: 597377428377
        Key: AutoOps/a609be2a47f42a79335713490c4b9961
      DefinitionSubstitutions:
        GetVolumeDetailsFunctionArn:
          Fn::GetAtt:
          - GetVolumeDetailsFunction
          - Arn
        ModifyVolumeSizeFunctionArn:
          Fn::GetAtt:
          - ModifyVolumeSizeFunction
          - Arn
        GetVolumeIdForWindowsFunctionArn:
          Fn::GetAtt:
          - GetVolumeIdForWindowsFunction
          - Arn
        GetVolumeIdForLinuxFunctionArn:
          Fn::GetAtt:
          - GetVolumeIdForLinuxFunction
          - Arn
        GetEbsAlarmDetailFunctionArn:
          Fn::GetAtt:
          - GetEbsAlarmDetailFunction
          - Arn
        GrowLinuxXfsFunctionArn:
          Fn::GetAtt:
          - GrowLinuxXfsFunction
          - Arn
        GrowWindowsNtfsFunctionArn:
          Fn::GetAtt:
          - GrowWindowsNtfsFunction
          - Arn
      Events:
        EBSSpaceAlarm:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.cloudwatch
              detail-type:
              - CloudWatch Alarm State Change
              detail:
                configuration:
                  metrics:
                    metricStat:
                      metric:
                        name:
                        - disk_used_percent
                        - LogicalDisk % Free Space
                state:
                  value:
                  - ALARM
        ApiEvent:
          Type: Api
          Properties:
            Path: /ebs_scale
            Method: POST
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GetVolumeDetailsFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: ModifyVolumeSizeFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GetVolumeIdForWindowsFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GetVolumeIdForLinuxFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GetEbsAlarmDetailFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GrowLinuxXfsFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GrowWindowsNtfsFunction
      Type: EXPRESS
  EC2AlarmCreatingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri:
        Bucket: 597377428377
        Key: AutoOps/64df633e086b206e037508978fdc4353
      DefinitionSubstitutions:
        GetInstanceDetailFunctionArn:
          Fn::GetAtt:
          - GetInstanceDetailFunction
          - Arn
        GetWindowsVolumesFunctionArn:
          Fn::GetAtt:
          - GetWindowsVolumesFunction
          - Arn
        GetLinuxVolumesFunctionArn:
          Fn::GetAtt:
          - GetLinuxVolumesFunction
          - Arn
        CreateLinuxDiskAlarmsFunctionArn:
          Fn::GetAtt:
          - CreateLinuxDiskAlarmsFunction
          - Arn
        CreateWindowsDiskAlarmsFunctionArn:
          Fn::GetAtt:
          - CreateWindowsDiskAlarmsFunction
          - Arn
      Events:
        EC2StateToRunning:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.ec2
              detail-type:
              - EC2 Instance State-change Notification
              detail:
                state:
                - running
        ApiEvent:
          Type: Api
          Properties:
            Path: /ec2_alarm_create
            Method: POST
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GetInstanceDetailFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GetWindowsVolumesFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: GetLinuxVolumesFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: CreateLinuxDiskAlarmsFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: CreateWindowsDiskAlarmsFunction
  GetVolumeDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: s3://597377428377/AutoOps/ff250e8b078b090975dc1db311009332
      Policies:
      - AmazonEC2ReadOnlyAccess
  ModifyVolumeSizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: s3://597377428377/AutoOps/51f4a4e796be44c0ae06a724171b024e
      Policies:
      - AmazonEC2FullAccess
  GetVolumeIdForLinuxFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: s3://597377428377/AutoOps/481be7fbec35cf1b82fca16634f6ce97
      Policies:
      - AmazonEC2ReadOnlyAccess
  GetVolumeIdForWindowsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 120
      CodeUri: s3://597377428377/AutoOps/3b987e845b79a090c669ff61139450dc
      Policies:
      - AmazonSSMFullAccess
  GetEbsAlarmDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: s3://597377428377/AutoOps/8e1bf6f2aa7eb132b93a52c11cb62b5f
  GrowLinuxXfsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: s3://597377428377/AutoOps/7b51e8f5f63b3777b3e5749f5f9bb8bf
      Policies:
      - AmazonSSMFullAccess
  GrowWindowsNtfsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: s3://597377428377/AutoOps/71c633bee9febb7307fa4522ae3a1b18
      Policies:
      - AmazonSSMFullAccess
  GetInstanceDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: s3://597377428377/AutoOps/d8e2ac6c5e52557c7d70ac4b06413c9d
      Policies:
      - AmazonEC2ReadOnlyAccess
  GetWindowsVolumesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 120
      CodeUri: s3://597377428377/AutoOps/71e1bc9c6170b2b8d8540ad0203d301e
      Policies:
      - AmazonSSMFullAccess
  GetLinuxVolumesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 120
      CodeUri: s3://597377428377/AutoOps/3736aba7160936c862385677c9592cd9
      Policies:
      - AmazonSSMFullAccess
  CreateLinuxDiskAlarmsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 120
      CodeUri: s3://597377428377/AutoOps/fe89eb438b5c5b0ba5ce2790768bea50
      Policies:
      - CloudWatchFullAccess
  CreateWindowsDiskAlarmsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 120
      CodeUri: s3://597377428377/AutoOps/a38e3be9ce00b541e544383e8bff11ae
      Policies:
      - CloudWatchFullAccess
Outputs:
  EBSScalingStateMachineArn:
    Description: EBS Autoscaling State machine ARN
    Value:
      Ref: EBSScalingStateMachine
  EC2AlarmCreatingStateMachineArn:
    Description: IAM Role created for EBS Autoscaling State machine based on the specified
      SAM Policy Templates
    Value:
      Ref: EC2AlarmCreatingStateMachine
  APIURL:
    Description: API URL
    Value:
      Ref: ServerlessRestApi
