AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AutoOps

  1.Increase volume and filesystem size when got a disk space alarm.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOps
    Description: A toolkit for auto ops in AWS.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: ['tests']
    SemanticVersion: 0.0.1
Resources:
  EBSAutoScalingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/ebs_autoscaling.asl.json
      DefinitionSubstitutions:
        GetVolumeDetailsFunctionArn: !GetAtt GetVolumeDetailsFunction.Arn
        ModifyVolumeSizeFunctionArn: !GetAtt ModifyVolumeSizeFunction.Arn
        GetVolumeIdFunctionArn: !GetAtt GetVolumeIdFunction.Arn
        GetEventDataFunctionArn: !GetAtt GetEventDataFunction.Arn
        GrowLinuxXfsFunctionArn: !GetAtt GrowLinuxXfsFunction.Arn
      Events:
        EBSSpaceAlarm:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.cloudwatch
              detail-type:
                - "CloudWatch Alarm State Change"
              detail:
                configuration: 
                  metrics:
                    metricStat:
                      metric:
                        name:
                          - "disk_used_percent"
                          - "LogicalDisk % Free Space"
                state:
                  value: 
                    - ALARM
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref GetVolumeDetailsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ModifyVolumeSizeFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetVolumeIdFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetEventDataFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GrowLinuxXfsFunction
  GetVolumeDetailsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetVolumeDetails
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: functions/GetVolumeDetails
      Policies: [AmazonEC2ReadOnlyAccess]
  ModifyVolumeSizeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ModifyVolumeSize
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: functions/ModifyVolumeSize
      Policies: [AmazonEC2FullAccess]
  GetVolumeIdFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetVolumeId
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: functions/GetVolumeId
      Policies: [AmazonEC2ReadOnlyAccess]
  GetEventDataFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetEventData
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: functions/GetEventData
  GrowLinuxXfsFunction:
    Type: 'AWS::Serverless::Function'
    Properties: 
      FunctionName: GrowLinuxXfs
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: functions/GrowLinuxXfs
      Policies: [AmazonSSMFullAccess]
Outputs:
  EBSAutoScalingStateMachineArn:
    Description: "EBS Autoscaling State machine ARN"
    Value: !Ref EBSAutoScalingStateMachine
  EBSAutoScalingStateMachineRoleArn:
    Description: "IAM Role created for EBS Autoscaling State machine based on the specified SAM Policy Templates"
    Value: !GetAtt EBSAutoScalingStateMachineRole.Arn




