
WSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AutoOps contains useful operational processes represented as a state machines with AWS StepFunctions.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOps
    Description: A toolkit for auto ops in AWS.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Resources:
  AutoOpsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: PRIVATE
      Auth:
        ResourcePolicy:
          SourceVpcWhitelist:
            - vpc-0f085c75
  EbsTagUpdatingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/EbsTagAutoUpdating/state.asl.json
      DefinitionSubstitutions:
        LoadEbsTagAutoUpdatingInputFunctionArn: !GetAtt LoadEbsTagAutoUpdatingInputFunction.Arn
        CreateEbsTagsFromEc2FunctionArn: !GetAtt CreateEbsTagsFromEc2Function.Arn      
      Events:
        EC2Running:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - "EC2 Instance State-change Notification"
              detail:
                state: 
                  - running
        ApiEvent:
          Type: Api
          Properties:
            Path: /ebs_tag_update
            Method: POST
            RestApiId:
              Ref: AutoOpsApiGateway
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadEbsTagAutoUpdatingInputFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateEbsTagsFromEc2Function

  CreateEbsTagsFromEc2Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: functions/CreateEbsTagsFromEc2
      Policies: [AmazonEC2FullAccess]
      Environment:
        Variables:
          TAGS_TO_SYNC: 'Name,Project'

  LoadEbsTagAutoUpdatingInputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: functions/LoadEbsTagAutoUpdatingInput


Outputs:
  APIEndpoint:
    Description: "APIGateway Endpoint to start start machines' execution"
    Value: !Join ["/", ["https:", "", !Join [".", [!Ref AutoOpsApiGateway, "execute-api", !Ref AWS::Region, "amazonaws.com"]], !Ref AutoOpsApiGatewayProdStage]]
