
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AutoOps contains useful operational processes represented as a state machines with AWS StepFunctions.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOps
    Description: A toolkit for auto ops in AWS.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Resources:
  AutoOpsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: PRIVATE
      Auth:
        ResourcePolicy:
          IpRangeWhitelist:
            - 172.31.0.0/16
  AutoOpsSnsTopic:
    Type: AWS::SNS::Topic
  CertComplianceChk:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/CertComplianceChk/state.asl.json
      DefinitionSubstitutions:
        LoadCertComplianceChkInputFunctionArn: !GetAtt LoadCertComplianceChkInputFunction.Arn
        NotifyCertExpiredFunctionArn: !GetAtt NotifyCertExpiredFunction.Arn
      Events:
        CertNonCompliant:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.config
              detail-type:
                - "Config Rules Compliance Change"
              detail:
                resourceType: 
                  - AWS::ACM::Certificate
                messageType:
                  - ComplianceChangeNotification
                newEvaluationResult:
                  complianceType:
                    - NON_COMPLIANT
        ApiEvent:
          Type: Api
          Properties:
            Path: /cert-non-comliant
            Method: POST
            RestApiId:
              Ref: AutoOpsApiGateway
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadCertComplianceChkInputFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifyCertExpiredFunction 

  LoadCertComplianceChkInputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: functions/LoadCertComplianceChkInput
  NotifyCertExpiredFunction:
    Type: 'AWS::Serverless::Function'
    Properties: 
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: functions/NotifyCertExpired
      Policies: [AmazonSNSFullAccess,AWSCertificateManagerReadOnly]
      Environment:
        Variables:
          SNS_TOPIC: !Ref AutoOpsSnsTopic

Outputs:
  APIEndpoint:
    Description: "APIGateway Endpoint to start status machines' execution"
    Value: !Join ["/", ["https:", "", !Join [".", [!Ref AutoOpsApiGateway, "execute-api", !Ref AWS::Region, "amazonaws.com"]], !Ref AutoOpsApiGatewayProdStage]]
