  EbsTagUpdatingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/EbsTagAutoUpdating/state.asl.json
      DefinitionSubstitutions:
        LoadEbsTagAutoUpdatingInputFunctionArn: !GetAtt LoadEbsTagAutoUpdatingInputFunction.Arn
        CreateEbsTagsFromEc2FunctionArn: !GetAtt CreateEbsTagsFromEc2Function.Arn      
      Events:
        EC2Running:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - "EC2 Instance State-change Notification"
              detail:
                state: 
                  - running
        ApiEvent:
          Type: Api
          Properties:
            Path: /ebs_tag_update
            Method: POST
            RestApiId:
              Ref: AutoOpsApiGateway
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadEbsTagAutoUpdatingInputFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateEbsTagsFromEc2Function
