  LoadCertComplianceChkInputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: functions/LoadCertComplianceChkInput