  EBSScalingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/EBSScaling/state.asl.json
      DefinitionSubstitutions:
        GetVolumeDetailsFunctionArn: !GetAtt GetVolumeDetailsFunction.Arn
        ModifyVolumeSizeFunctionArn: !GetAtt ModifyVolumeSizeFunction.Arn
        GetVolumeIdForWindowsFunctionArn: !GetAtt GetVolumeIdForWindowsFunction.Arn
        GetVolumeIdForLinuxFunctionArn: !GetAtt GetVolumeIdForLinuxFunction.Arn
        LoadEbsAutoScalingInputFunctionArn: !GetAtt LoadEbsAutoScalingInputFunction.Arn
        GrowLinuxXfsFunctionArn: !GetAtt GrowLinuxXfsFunction.Arn
        GrowWindowsNtfsFunctionArn: !GetAtt GrowWindowsNtfsFunction.Arn
      Events:
        EBSSpaceAlarm:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.cloudwatch
              detail-type:
                - "CloudWatch Alarm State Change"
              detail:
                configuration: 
                  metrics:
                    metricStat:
                      metric:
                        name:
                          - "disk_used_percent"
                          - "LogicalDisk % Free Space"
                state:
                  value: 
                    - ALARM
        ApiEvent:
          Type: Api
          Properties:
            Path: /ebs_scale
            Method: POST
            RestApiId:
              Ref: AutoOpsApiGateway
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref GetVolumeDetailsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ModifyVolumeSizeFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetVolumeIdForWindowsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetVolumeIdForLinuxFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadEbsAutoScalingInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GrowLinuxXfsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GrowWindowsNtfsFunction
